# Generated by Django 2.1.7 on 2019-10-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191011_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founder',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='loser',
            old_name='image',
            new_name='img',
        ),
    ]
